Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /uiuzpucwPQkw
Not Found: /
Not Found: /OuvTJJcyjzbsp
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Bad Request: /api/token/
Bad Request: /api/token/
[ERROR] [UID:1113][1599625] wsgiAppHandler pApp->start_response() return NULL.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/whitenoise/middleware.py", line 123, in __call__
    return self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/corsheaders/middleware.py", line 56, in __call__
    result = self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python39/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/it_helpdesk/urls.py", line 21, in <module>
    from api import urls as apiurls
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/urls.py", line 3, in <module>
    from . import views
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 44, in <module>
    from .serializers import CustomTokenRefreshSerializer, DepartmentSerializer, PasswordResetConfirmSerializer, PasswordResetRequestSerializer, RecentTicketSerializer, ReportTicketSerializer, TicketCategorySerializer, TicketCommentSerializer, TicketHistorySerializer, TicketSerializer, UserCreateSerializer, UserGetSerializer, UserSerializer
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/serializers.py", line 228, in <module>
    class AcknowledgementSerializer(serializers.modelSerializer):
AttributeError: module 'rest_framework.serializers' has no attribute 'modelSerializer'
Forbidden: /api/acknowledgement/1/
Internal Server Error: /api/acknowledgement/1/
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1269, in acknowledgement
    acknowledgement = Acknowledgement.objects.filter(ticket=ticket_id)
NameError: name 'Acknowledgement' is not defined
Internal Server Error: /api/acknowledgement/1/
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1269, in acknowledgement
    acknowledgement = Acknowledgement.objects.filter(ticket=ticket_id)
NameError: name 'Acknowledgement' is not defined
Not Found: /
Not Found: /favicon.ico
Forbidden (CSRF cookie not set.): /admin/login/
Forbidden (CSRF cookie not set.): /admin/login/
Forbidden (CSRF cookie not set.): /admin/login/
Not Found: /
Not Found: /favicon.ico
Not Found: /api/acknowledgement
Forbidden: /api/list_ticket_category/
Not Found: /api/acknowledgement/
Internal Server Error: /api/list_acknowledgements/
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1290, in list_acknowledgements
    # acknowledgements = Acknowledgement.objects.all()
NameError: name 'Acknowledgement' is not defined
Not Found: /list_acknowlegement/
Unauthorized: /api/my_ticket/
Internal Server Error: /api/list_acknowledgements/
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1290, in list_acknowledgements
    acknowledgements = Acknowledgement.objects.all()
NameError: name 'Acknowledgement' is not defined
Internal Server Error: /api/list_acknowledgements/
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1290, in list_acknowledgements
    acknowledgements = Acknowledgement.objects.all()
NameError: name 'Acknowledgement' is not defined
Unauthorized: /api/my_ticket/
Not Found: /api/lacknowledgement/23
Not Found: /api/lacknowledgement/23/
Unauthorized: /api/create_acknowledgement/
Method Not Allowed: /api/acknowledgement/23/
Unauthorized: /api/create_acknowledgement/
Unauthorized: /api/create_acknowledgement/
Unauthorized: /api/create_acknowledgement/
Unauthorized: /api/create_acknowledgement/
Unauthorized: /api/create_acknowledgement/
Method Not Allowed: /api/create_acknowledgement/
Bad Request: /api/create_acknowledgement/
Bad Request: /api/create_acknowledgement/
Unauthorized: /api/create_acknowledgement/
Unauthorized: /api/create_acknowledgement/
Not Found: /favicon.ico
Internal Server Error: /api/report/tickets/
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1086, in TicketReportView
    return generate_excel_report(tickets, avg_response_time, avg_fixing_time)
  File "/home/awashwinesinfo/backend.ithelpdesk.awashwines.info/server/api/views.py", line 1101, in generate_excel_report
    df['created_at'] = df['created_at'].apply(lambda x: x.replace(tzinfo=None))
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib64/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib64/python3.9/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'created_at'
Bad Request: /api/token/
Sending SMS to 0969946721
sending email to mikiyast@awashwine.com
Not Found: /
Not Found: /
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /wp
Not Found: /wordpress
Not Found: /backend
Not Found: /wordpress
Not Found: /old
Not Found: /backup
Not Found: /new
Not Found: /test
Not Found: /wp
Not Found: /temp
Not Found: /blog
Not Found: /
Not Found: /
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /robots.txt
Not Found: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /sftp-config.json
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /.vscode/sftp.json
Bad Request: /api/token/
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /ads.txt
[UID:1113][2006742] Child process with pid: 2006831 was killed by signal: 15, core dumped: no
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /robots.txt
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /sitemap.xml
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/awashwinesinfo/virtualenv/backend.ithelpdesk.awashwines.info/server/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.backend.ithelpdesk.awashwines.info'. You may need to add 'www.backend.ithelpdesk.awashwines.info' to ALLOWED_HOSTS.
Bad Request: /robots.txt
Not Found: /
Not Found: /favicon.ico
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /
Not Found: /favicon.ico
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /
Bad Request: /api/change_password/MjI/ab3c8cdb-c77f-439c-9053-6b0e49e321cc/
Bad Request: /api/change_password/MjI/ab3c8cdb-c77f-439c-9053-6b0e49e321cc/
Bad Request: /api/change_password/MjI/ab3c8cdb-c77f-439c-9053-6b0e49e321cc/
Bad Request: /api/change_password/MjI/ab3c8cdb-c77f-439c-9053-6b0e49e321cc/
Not Found: /
Not Found: /favicon.ico
Forbidden: /api/admin-dashboard/
Bad Request: /api/token/
Forbidden: /api/list_ticket_category/
Forbidden: /api/download_attachment/31
Forbidden: /api/download_attachment/31
Forbidden: /api/list_ticket_category/
Forbidden: /api/list_ticket_category/
Sending SMS to 0969946721
sending email to mikiyast@awashwine.com
message sent
Not Found: /sftp-config.json
Not Found: /.vscode/sftp.json
Not Found: /
Not Found: /favicon.ico
Unauthorized: /api/
Not Found: /
Not Found: /create_acknowledgment/
Not Found: /create_acknowledgement/
Method Not Allowed: /api/token/
Not Found: /create_acknowledgement/
Not Found: /create_acknowledgement/
Not Found: /create_acknowledgement/
Not Found: /token/
Not Found: /token/
Not Found: /token/
Not Found: /token/
Not Found: /token
Not Found: /token/
Not Found: /token/
Not Found: /token/
Not Found: /token/
